### ISSUE TITLE
OpenWebStart rejects/discards "--add-opens" java argument (Java 11)

### ISSUE THREAD

**Issue by rchfox** [karakun/OpenWebStart#322]
Hello,

I'm using OpenWebStart 1.2.1, which installs AdoptOpenJDK-1.8.0 as its default JRE. My OS is Linux Ubuntu 20.04.1 (Xubuntu flavor). 

Here the relevant `<java ... />` element, with its `java-vm-args` attribute within my JNLP file:
```xml
<resources>
   <java version="11+" java-vm-args="--add-opens=jdk.crypto.cryptoki/sun.security.pkcs11.wrapper=ALL-UNNAMED"/>
   <jar href="xxxxx" main="true"/>
   <jar href="yyyyy" />
   <jar href="zzzzz" />
   ....
</resources>
``` 
OpenWebStart rightfully downloaded Java 11.0.7, and my app is always launched with Java 11, as expected. That part of the process is OK. 

**The problem**:  Just before launching my app, OpenWebStarts discards the `--add-opens` argument read from my JNLP file. 

**The cause (?)**:  Before launching my app, OpenWebStarts apparently performs some kind of validity test for the arguments included in `java-vm-args`, but it does it using its bundled JRE, instead of doing it using the requested JRE. Since `--add-opens` is an option introduced with Java 9, it is unrecognized by the bundled Java 1.8.0, then it's just plain discarded.  

Here the relevant lines of my OpenWebStart log (clearly you can see that `--add-opens` is probed with Java 1.8.0 and discarded, and afterwards OpenWebStart switches to Java 11):
      
```log
[ITW-CORE][2020-09-02 19:31:29.099 PYT][WARN ][net.sourceforge.jnlp.Parser] Warning - your JRE - 1.8.0_252 - does not match requested JRE - 11+
[ITW-CORE][2020-09-02 19:31:29.109 PYT][WARN ][net.sourceforge.jnlp.Parser] Ignoring java-vm-args due to illegal Property --add-opens=jdk.crypto.cryptoki/sun.security.pkcs11.wrapper=ALL-UNNAMED
.....
.....
[ITW-CORE][2020-09-02 19:31:31.662 PYT][DEBUG][com.openwebstart.launcher.OwsJvmLauncher] searching for JRE with version string '11*' and vendor '*'
[ITW-CORE][2020-09-02 19:31:31.665 PYT][DEBUG][com.openwebstart.jvm.JavaRuntimeSelector] Trying to find Java runtime. Requested version: '11*', vendor: '*', os: 'LINUX64', server-url: 'null'
.....
.....
[ITW-CORE][2020-09-02 19:31:33.705 PYT][DEBUG][com.openwebstart.launcher.OwsJvmLauncher] Found JVM JavaRuntime{version=11.0.7, vendor=Azul Systems, Inc., operationSystem=LINUX64}
[ITW-CORE][2020-09-02 19:31:33.712 PYT][INFO ][com.openwebstart.launcher.OwsJvmLauncher] using java runtime at '/home/rchfox/.cache/icedtea-web/jvm-cache/azul_11.0.7' for launching managed application
[ITW-CORE][2020-09-02 19:31:33.759 PYT][DEBUG][com.openwebstart.jvm.LocalRuntimeManager] Replacing runtime definition with new one
[ITW-CORE][2020-09-02 19:31:33.760 PYT][DEBUG][com.openwebstart.jvm.LocalRuntimeManager] Saving runtime cache to filesystem
[ITW-CORE][2020-09-02 19:31:33.765 PYT][INFO ][com.openwebstart.launcher.OwsJvmLauncher] About to launch external with commands:  ......
```

I've made a lot of testing before posting this issue. I know for sure that the root of this problem is in Java versions < 9 not recognizing the `--add-opens` argument. This argument works fine with Java 9, 10, 11, 12, 13 and 14. I fact, the purpose of `--add-opens`  is to support migration from Java versions < 9, as documented in the Migration Guides:
[Java 9 Migration Guide](https://docs.oracle.com/javase/9/migrate/)
[Java 10 Migration Guide](https://docs.oracle.com/javase/10/migrate/)
[Java 11 Migration Guide](https://docs.oracle.com/en/java/javase/11/migrate/)
[Java 12 Migration Guide](https://docs.oracle.com/en/java/javase/12/migrate/)
[Java 13 Migration Guide](https://docs.oracle.com/en/java/javase/13/migrate/)
[Java 14 Migration Guide](https://docs.oracle.com/en/java/javase/14/migrate/)  

**My questions**:

1. Is this behavior by design? If so, would you please explain why?
2. If this is not by design, could it be fixed without much effort?
3. Is there any workaround that I could do to make javaws launch my app with the `--add-opens` argument? 

Thank you in advance.

**Comment by sclassen** [comment]
Thank you for reporting this.
We can confirm that this is a bug and will be fixed in the next release.
Most likely in November 2020

**Comment by rchfox** [comment]
Thank you @sclassen for your prompt response! 
I really appreciate it. I'll be looking forward to the fix.

**Comment by sclassen** [comment]
fixed in https://github.com/AdoptOpenJDK/IcedTea-Web/pull/704/files

**Comment by harbingerofdoom** [comment]
I am using Java version 17 and using java-vm-args="--add-opens=java.desktop/sun.font=ALL-UNNAMED in openwebstart. 
But it doesn't work.
Is the issue fixed?

**Comment by cryptofuse** [comment]
I see the same issue with Java version 17 -I can confirm that the root cause appears to be exactly the  issue described by the OP - the OWS packaged JRE prevents the add-opens from being processed and not the JDK used to run the JWS app.  This is not yet fixed (running OWS 1.5 (packaged with JRE Temurin build 1.8.0_312-b07).

**Comment by sclassen** [comment]
Please post a log file if you think this issue still affects you.
You can also send log files to openwebstart@karakun.com mentioning the github issue.

**Comment by cryptofuse** [comment]
Hi @sclassen, I updated my message above to include the key log messages as requested.
